import { useState } from 'react'
import { Navigate, useNavigate, useParams } from 'react-router'
import AppShell from '../components/AppShell'
import { doctors, slots } from '../data/mockData'
import { getMockRole } from '../lib/mockSession'

function BookingPage() {
  const { id } = useParams()
  const doctor = doctors.find((item) => item.id === id) ?? doctors[0]
  const [slot, setSlot] = useState(slots[0])
  const navigate = useNavigate()
  if (getMockRole() !== 'patient') return <Navigate replace to={`/login?next=/reserva/${doctor.id}`} />
  return <AppShell role="patient"><div className="mx-auto max-w-3xl"><p className="text-sm font-semibold text-cyan-700">RESERVA DE CITA</p><h1 className="mt-1 text-3xl font-semibold text-slate-900">Elige el horario que prefieras</h1><div className="mt-7 grid gap-6 md:grid-cols-[1fr_0.8fr]"><section className="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><h2 className="font-semibold text-slate-900">1. Selecciona una fecha</h2><div className="mt-4 grid grid-cols-3 gap-2 sm:grid-cols-5">{['Lun 21', 'Mar 22', 'Mié 23', 'Jue 24', 'Vie 25'].map((day, index) => <button className={`rounded-xl border px-2 py-3 text-sm font-medium ${index === 0 ? 'border-cyan-600 bg-cyan-50 text-cyan-800' : 'border-slate-200 text-slate-600'}`} key={day} type="button">{day}</button>)}</div><h2 className="mt-8 font-semibold text-slate-900">2. Selecciona una hora</h2><div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-3">{slots.map((item) => <button className={`rounded-xl border px-3 py-3 text-sm font-medium ${slot === item ? 'border-cyan-600 bg-cyan-600 text-white' : 'border-slate-200 text-slate-600 hover:border-cyan-300'}`} key={item} onClick={() => setSlot(item)} type="button">{item}</button>)}</div><h2 className="mt-8 font-semibold text-slate-900">3. Motivo de consulta</h2><textarea className="mt-3 min-h-24 w-full rounded-xl border border-slate-200 p-3 text-sm outline-none focus:border-cyan-600" placeholder="Escribe brevemente el motivo de tu consulta" /></section><aside className="h-fit rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><p className="text-sm text-slate-500">Resumen de la cita</p><h2 className="mt-3 text-lg font-semibold">{doctor.name}</h2><p className="mt-1 text-sm text-cyan-700">{doctor.specialty}</p><dl className="mt-6 space-y-3 border-y border-slate-100 py-5 text-sm"><div className="flex justify-between gap-3"><dt className="text-slate-500">Fecha</dt><dd className="font-medium">Lunes, 21 sept.</dd></div><div className="flex justify-between gap-3"><dt className="text-slate-500">Hora</dt><dd className="font-medium">{slot}</dd></div><div className="flex justify-between gap-3"><dt className="text-slate-500">Modalidad</dt><dd className="font-medium">Presencial</dd></div></dl><button className="mt-6 w-full rounded-xl bg-cyan-600 px-4 py-3 font-semibold text-white hover:bg-cyan-700" onClick={() => navigate('/confirmacion')} type="button">Confirmar cita</button></aside></div></div></AppShell>
}
export default BookingPage
