import { Link } from 'react-router'
import AppShell from '../components/AppShell'

const appointments = [{ time: '09:00', patient: 'Mariana Flores', detail: 'Consulta de control' }, { time: '10:30', patient: 'Diego Paredes', detail: 'Dolor de garganta' }, { time: '03:00', patient: 'Lucía Ramos', detail: 'Consulta general' }]

function DoctorHomePage() {
  return <AppShell role="doctor"><section className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-semibold text-cyan-700">LUNES, 21 DE SEPTIEMBRE</p><h1 className="mt-1 text-3xl font-semibold text-slate-900">Buenos días, Dra. Valeria</h1><p className="mt-2 text-slate-500">Este es el resumen de tu agenda de hoy.</p></div><Link className="rounded-xl bg-cyan-600 px-4 py-3 text-sm font-semibold text-white hover:bg-cyan-700" to="/doctor/horarios">Configurar horarios</Link></section><section className="mt-8 grid gap-4 sm:grid-cols-3"><article className="rounded-2xl bg-cyan-700 p-5 text-white"><p className="text-sm text-cyan-100">Citas de hoy</p><p className="mt-2 text-3xl font-semibold">8</p></article><article className="rounded-2xl bg-white p-5 ring-1 ring-slate-200"><p className="text-sm text-slate-500">Próxima cita</p><p className="mt-2 text-lg font-semibold">09:00 a. m.</p></article><article className="rounded-2xl bg-white p-5 ring-1 ring-slate-200"><p className="text-sm text-slate-500">Horas disponibles</p><p className="mt-2 text-lg font-semibold">5 esta semana</p></article></section><section className="mt-8 rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><div className="flex items-center justify-between"><div><h2 className="text-xl font-semibold">Agenda de hoy</h2><p className="mt-1 text-sm text-slate-500">Tus próximas atenciones</p></div><span className="rounded-full bg-cyan-50 px-3 py-1 text-sm text-cyan-700">3 citas</span></div><div className="mt-6 divide-y divide-slate-100">{appointments.map((item) => <article className="flex flex-wrap items-center gap-4 py-4" key={item.time}><time className="w-16 font-semibold text-cyan-700">{item.time}</time><div className="grid size-10 place-items-center rounded-full bg-slate-100 font-semibold text-slate-600">{item.patient[0]}</div><div className="flex-1"><h3 className="font-medium text-slate-900">{item.patient}</h3><p className="text-sm text-slate-500">{item.detail}</p></div><button className="rounded-lg border border-slate-200 px-3 py-2 text-sm font-medium text-slate-600" type="button">Ver ficha</button></article>)}</div></section></AppShell>
}
export default DoctorHomePage
