import { useMemo, useState } from 'react'
import { Link } from 'react-router'
import AppShell from '../components/AppShell'
import { doctors, specialties } from '../data/mockData'

function PatientHomePage() {
  const [specialty, setSpecialty] = useState('Todas')
  const [location, setLocation] = useState('')
  const visibleDoctors = useMemo(() => doctors.filter((doctor) => (specialty === 'Todas' || doctor.specialty === specialty) && doctor.location.toLowerCase().includes(location.toLowerCase())), [location, specialty])

  return <AppShell role="patient"><section className="rounded-3xl bg-cyan-700 px-6 py-9 text-white sm:px-10"><p className="text-sm font-semibold tracking-wide text-cyan-100">ENCUENTRA ATENCIÓN MÉDICA</p><h1 className="mt-2 max-w-xl text-3xl font-semibold tracking-tight sm:text-4xl">Agenda una cita con el especialista ideal para ti.</h1><div className="mt-7 grid gap-3 rounded-2xl bg-white p-3 shadow-lg md:grid-cols-[1fr_1fr_auto]"><select aria-label="Especialidad" className="rounded-xl border-0 bg-slate-50 px-4 py-3 text-slate-700 outline-none" onChange={(event) => setSpecialty(event.target.value)} value={specialty}>{specialties.map((item) => <option key={item}>{item}</option>)}</select><input aria-label="Ubicación" className="rounded-xl bg-slate-50 px-4 py-3 text-slate-700 outline-none placeholder:text-slate-400" onChange={(event) => setLocation(event.target.value)} placeholder="Ubicación: Miraflores, Lima" /><button className="rounded-xl bg-cyan-600 px-6 py-3 font-semibold hover:bg-cyan-800" type="button">Buscar</button></div></section><section className="mt-10"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-sm font-semibold text-cyan-700">ESPECIALISTAS</p><h2 className="mt-1 text-2xl font-semibold text-slate-900">Profesionales disponibles</h2></div><p className="text-sm text-slate-500">{visibleDoctors.length} resultados</p></div><div className="mt-6 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{visibleDoctors.map((doctor) => <article className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm" key={doctor.id}><div className="flex gap-4"><div className={`grid size-14 shrink-0 place-items-center rounded-full text-lg font-semibold ${doctor.color}`}>{doctor.name.split(' ').at(-1)?.[0]}</div><div><h3 className="font-semibold text-slate-900">{doctor.name}</h3><p className="mt-1 text-sm text-cyan-700">{doctor.specialty}</p><p className="mt-2 text-sm text-slate-500">★ {doctor.rating} · {doctor.location}</p></div></div><p className="mt-5 text-sm text-slate-500">Próxima disponibilidad: <span className="font-medium text-slate-700">Hoy, 3:00 p. m.</span></p><div className="mt-5 flex gap-3"><Link className="flex-1 rounded-xl border border-slate-200 px-3 py-2.5 text-center text-sm font-semibold text-slate-700 hover:bg-slate-50" to={`/doctores/${doctor.id}`}>Ver perfil</Link><Link className="flex-1 rounded-xl bg-cyan-600 px-3 py-2.5 text-center text-sm font-semibold text-white hover:bg-cyan-700" to={`/reserva/${doctor.id}`}>Reservar</Link></div></article>)}</div></section></AppShell>
}

export default PatientHomePage
