import { useState } from 'react'
import AppShell from '../components/AppShell'

const days = ['Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes']
function SchedulePage() {
  const [enabled, setEnabled] = useState<Record<string, boolean>>({ Lunes: true, Martes: true, Miércoles: true, Jueves: false, Viernes: true })
  return <AppShell role="doctor"><p className="text-sm font-semibold text-cyan-700">DISPONIBILIDAD</p><h1 className="mt-1 text-3xl font-semibold text-slate-900">Configura tu semana</h1><p className="mt-2 text-slate-500">Define los bloques en los que aceptarás nuevas citas.</p><section className="mt-8 rounded-2xl bg-white shadow-sm ring-1 ring-slate-200"><div className="border-b border-slate-100 p-6"><h2 className="font-semibold">Pool de horarios</h2><p className="mt-1 text-sm text-slate-500">Semana del 21 al 25 de septiembre</p></div><div className="divide-y divide-slate-100">{days.map((day) => <div className="flex flex-wrap items-center gap-4 p-5" key={day}><button aria-pressed={enabled[day]} className={`relative h-6 w-11 rounded-full transition ${enabled[day] ? 'bg-cyan-600' : 'bg-slate-200'}`} onClick={() => setEnabled((current) => ({ ...current, [day]: !current[day] }))} type="button"><span className={`absolute top-1 size-4 rounded-full bg-white transition ${enabled[day] ? 'left-6' : 'left-1'}`} /></button><p className="w-28 font-medium text-slate-900">{day}</p>{enabled[day] ? <div className="flex flex-1 flex-wrap items-center gap-3"><span className="rounded-lg bg-cyan-50 px-3 py-2 text-sm text-cyan-800">09:00 - 12:00</span><span className="rounded-lg bg-cyan-50 px-3 py-2 text-sm text-cyan-800">14:00 - 18:00</span><button className="text-sm font-semibold text-cyan-700" type="button">+ Agregar bloque</button></div> : <p className="text-sm text-slate-400">No disponible</p>}</div>)}</div><div className="flex justify-end border-t border-slate-100 p-5"><button className="rounded-xl bg-cyan-600 px-5 py-3 font-semibold text-white" type="button">Guardar horarios</button></div></section></AppShell>
}
export default SchedulePage
